# Generated by Django 4.2.2 on 2023-06-06 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=123)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.livro')),
            ],
        ),
    ]
